/*
 * locals.js - HeyGen 中文汉化词典
 * Home: https://github.com/a18367883388/heygen-chinese
 */
var HEYGEN_CHINESE_LOCALES = {
  // 首页 / 导航
  "Home": "首页",
  "Avatar": "数字人",
  "Video Agent": "视频智能体",
  "Translate": "翻译",
  "Brand": "品牌",
  "Apps": "应用",
  "Projects": "项目",
  "Quick create": "快速创建",
  "Avatars": "我的数字人",
  "AI Studio": "AI 工作室",
  "Avatar Shots": "数字人镜头",
  "Voices": "声音",
  "PPT/PDF to video": "PPT/PDF 转视频",
  "Recents": "最近",
  "See all": "查看全部",
  "Drafts": "草稿",
  "Recent": "最近",

  // 首页功能卡片
  "Build a video scene by scene": "逐场景搭建视频",
  "Take full control over your avatar, script, scenes, layout, and more": "完整控制数字人、脚本、场景、布局等",
  "Generate a video from a prompt": "从提示词生成视频",
  "AI can write the script, create b-roll, use your avatar, and much more": "AI 自动写脚本、生成 B-roll、调用数字人等",
  "Make an avatar video from a photo": "用照片生成数字人视频",
  "Use a photo for your avatar.": "上传一张照片即可生成数字人。",
  "Create your AI avatar": "创建你的 AI 数字人",
  "Record, upload, or describe your avatar to life": "录制、上传或描述，生成专属数字人",
  "Translate any video": "翻译任意视频",
  "175+ languages and dialects in natural voice and lip sync": "支持 175+ 语言，自然声音与嘴型同步",
  "Start with a template": "从模板开始",
  "Ready-made layouts for presentations, explainers, and more": "提供演示、说明等多种现成布局",
  "Edit as New": "复制并编辑",
  "See all projects": "查看全部项目",

  // 视频编辑器
  "Script": "脚本",
  "Add scene": "添加场景",
  "Delivery style": "播报风格",
  "Brand System": "品牌系统",
  "Generate": "生成",
  "Render Scene": "渲染场景",
  "Avatar & Voice": "数字人与声音",
  "No Avatar": "未选择数字人",
  "Add avatar": "选择数字人",
  "Voice": "声音",
  "Select Voice": "选择声音",
  "Motion Engine": "动作引擎",
  "Avatar Background": "数字人背景",
  "Customize": "自定义背景",
  "Remove": "移除背景",
  "Color": "纯色背景",
  "Layout": "布局",
  "Original": "原始",
  "Circle": "圆形",
  "Radius": "圆角",
  "Zoom": "缩放",
  "Final lip-sync shows after video is generated": "嘴型同步将在视频生成后展示",
  "How does this voice sound?": "这个声音怎么样？",
  "AI Tools": "AI 工具",
  "Media": "媒体",
  "Elements": "元素",
  "Music": "音乐",
  "Captions": "字幕",
  "Screen Recorder": "屏幕录制",
  "Templates": "模板",
  "Layers": "图层",
  "Interactivity": "交互",

  // 数字人管理
  "My Avatars": "我的数字人",
  "Public Avatars": "公共数字人",
  "New Avatar": "新建数字人",
  "Add a look": "添加形象",
  "Edit Look": "编辑形象",
  "Use in video": "在视频中使用",
  "Build scene-by-scene": "逐场景搭建",
  "Add a script": "添加脚本",
  "Use with prompt": "用提示词生成",
  "Create new shots": "创建新镜头",
  "Replace avatar": "更换数字人",
  "Create Avatar": "创建数字人",
  "Create a new avatar": "创建新数字人",
  "Record via webcam": "用摄像头录制",
  "Record via phone": "用手机录制",
  "upload footage": "上传素材",
  "I'm ready": "我准备好了",
  "Your Avatar is ready to use!": "你的数字人已就绪！",
  "Choose your avatar's voice, then start creating videos!": "选择声音后，即可开始制作视频！",
  "New voice": "新建声音",
  "Recommended": "推荐",
  "Get the best voice by creating a separate voice clone.": "单独录制声音克隆，效果更佳。",
  "Record voice": "录制声音",
  "Voice from footage": "使用素材中的声音",
  "Use this voice": "使用此声音",

  // 声音管理
  "Clone your voice": "克隆你的声音",
  "Design a voice": "设计声音",
  "Import from 3rd party": "从第三方导入",
  "My voices": "我的声音",
  "HeyGen library": "HeyGen 声音库",
  "Voice Clone": "声音克隆",
  "Save this voice": "保存此声音",
  "Re-record": "重新录制",
  "VOICE SETTINGS": "声音设置",
  "Speed": "语速",
  "Volume": "音量",
  "Voice engine": "声音引擎",
  "Accent": "语言/口音",
  "Save changes": "保存更改",
  "Original audio quality": "原始音频质量",
  "GOOD": "良好",
  "Sounds too flat": "声音太平",
  "Doesn't sound like me": "不像我的声音",
  "Poor audio quality": "音频质量差",
  "Wrong accent": "口音不对",

  // 生成视频弹窗
  "Generate Video": "生成视频",
  "Title": "标题",
  "Add to folder": "添加到文件夹",
  "Resolution": "分辨率",
  "Fps": "帧率",
  "Format": "格式",
  "Submit": "提交",
  "Cancel": "取消",
  "HeyGen Watermark": "HeyGen 水印",
  "This will use one free Avatar video quota.": "此操作将消耗 1 个免费视频配额。",
  "Available:": "剩余：",
  "video(s)": "个视频",

  // 视频详情页
  "Edit": "编辑",
  "Activity": "动态",
  "Transcript": "文字稿",
  "Make Edits": "编辑视频",
  "New revision in AI Studio": "在 AI 工作室中修改",
  "Upscale Video": "视频超清化",
  "Change Thumbnail": "更改封面",
  "Summary": "摘要",
  "views": "次观看",
  "Share": "分享",

  // 身份验证
  "Verify identity": "身份验证",
  "To prevent misuse, we'll confirm you have the right to use this avatar in videos.": "为防止滥用，我们需要确认您有权使用此数字人形象。",
  "Upload consent": "上传授权视频",
  "Please record a quick video reading the following script": "请录制一段视频，朗读以下验证码",
  "Turn on Cam & Mic": "开启摄像头和麦克风",
  "Your browser may ask for permission to use your camera and microphone.": "浏览器将请求使用您的摄像头和麦克风权限。",
  "Start Recording": "开始录制",
  "Please make sure you read out the code correctly.": "请确保清晰朗读验证码。",
  "Video under review": "视频审核中",
  "This video contains an avatar that is currently being reviewed. It will be available once the review is complete.": "此视频包含正在审核的数字人，审核完成后即可使用。",
  "Go to HeyGen": "返回 HeyGen",

  // 付费计划
  "Plans that fit your scale": "选择适合你的方案",
  "Individual": "个人版",
  "Business": "企业版",
  "Current Plan": "当前方案",
  "Get Started": "立即开始",
  "Video Generation:": "视频生成：",
  "videos per month": "个视频/月",
  "Videos up to": "视频时长最长",
  "video export": "视频导出",
  "Faster video processing": "更快的视频处理速度",
  "Unlimited Photo Avatars": "无限照片数字人",
  "Watermark removal": "去除水印",
  "Voice Cloning": "声音克隆",
  "Credit rollovers": "积分结转",
  "Everything in Free, plus:": "免费版全部功能，另加：",
  "Everything in Creator, plus:": "创作者版全部功能，另加：",
  "Customizable monthly usage": "自定义月度用量",
  "See full comparison": "查看完整对比",
  "billed yearly": "按年计费",
  "Looking for API plans?": "需要 API 方案？",
  "Features you'll love:": "你会喜欢的功能：",
  "Custom Digital Twin": "自定义数字分身",
  "languages": "种语言",
  "monthly credits": "积分/月",
  "Stock Digital Twins": "预设数字人",

  // 通用按钮 / 状态
  "Loading...": "加载中...",
  "Save": "保存",
  "Delete": "删除",
  "Download": "下载",
  "Upload": "上传",
  "Back": "返回",
  "Next": "下一步",
  "Done": "完成",
  "Close": "关闭",
  "Confirm": "确认",
  "New": "新",
  "DRAFT": "草稿",
  "Processing": "处理中",
  "Completed": "已完成",
  "Failed": "失败",
  "Upgrade to Creator": "升级到创作者版",
  "Upgrade to Creator to unlock this feature": "升级到创作者版以解锁此功能",
  "Get Creator + 1 Avatar Add-on": "获取创作者版 + 1 个数字人附加包",
  "Subscribe": "订阅",
  "Log out": "退出登录",
  "Settings": "设置",
  "Profile": "个人资料",
  "Billing": "账单",
  "API": "API",
  "Help": "帮助",
  "Feedback": "反馈"
};

if (typeof window !== 'undefined') {
  window.HEYGEN_CHINESE_LOCALES = HEYGEN_CHINESE_LOCALES;
}
